---
# https://taskfile.dev

version: "3"

vars:
  GO_LD_FLAGS: -w -s
  BINARY_DIR: dist
  BINARY_NAME: pipe
  BINARY_APPEND_OS: true
  BINARY_APPEND_ARCH: true

env:
  GO_VERSION: 1.25
  CGO_ENABLED: 0

includes:
  go:
    taskfile: https://gitlab.kilic.dev/libraries/taskfiles/-/raw/main/Taskfile.go-application.yml?ref_type=heads
    flatten: true

tasks:
  build:
    desc: Builds the application.
    cmds:
      - task: build.platform
        vars:
          GO_LD_FLAGS: -w -s -X main.VERSION=BUILD.$(date +%Y%m%dT%H%M%S)
          BINARY_DIR: dist
          BINARY_NAME: pipe
          BINARY_APPEND_OS: true
          BINARY_APPEND_ARCH: true
          os: linux
          arch: amd64

  docs:
    desc: Generates the documentation for the application.
    interactive: true
    env:
      LOG_LEVEL: trace
    cmds:
      - go run . MARKDOWN_DOC
      - go run . MARKDOWN_EMBED

  help:
    desc: Generates help for the application.
    cmds:
      - go run . --help

  docker.build:
    desc: Builds the docker container for the application for testing.
    cmds:
      - docker compose build
    sources:
      - "dist/**"
      - "Dockerfile*"
      - "docker-compose*.yml"

  docker.up:
    desc: Runs the docker-compose application.
    interactive: true
    cmds:
      - task: build
      - task: docker.build
      - docker compose up
